# node exporter and its dependencies
/usr/include/nntrainer/nntrainer_error.h
/usr/include/nntrainer/connection.h
/usr/include/nntrainer/common_properties.h
/usr/include/nntrainer/base_properties.h
/usr/include/nntrainer/node_exporter.h
/usr/include/nntrainer/profiler.h
/usr/include/nntrainer/nntr_threads.h
# tensor headers
/usr/include/nntrainer/memory_data.h
/usr/include/nntrainer/tensor.h
/usr/include/nntrainer/tensor_base.h
/usr/include/nntrainer/char_tensor.h
/usr/include/nntrainer/short_tensor.h
/usr/include/nntrainer/float_tensor.h
/usr/include/nntrainer/tensor_wrap_specs.h
/usr/include/nntrainer/blas_interface.h
/usr/include/nntrainer/var_grad.h
/usr/include/nntrainer/weight.h
# todo: update dataset headers
/usr/include/nntrainer/databuffer.h
/usr/include/nntrainer/databuffer_factory.h
# layer headers
/usr/include/nntrainer/layer_context.h
/usr/include/nntrainer/layer_devel.h
/usr/include/nntrainer/layer_impl.h
/usr/include/nntrainer/acti_func.h
# custom layer kits
/usr/include/nntrainer/app_context.h
# logger
/usr/include/nntrainer/nntrainer_log.h
/usr/include/nntrainer/nntrainer_logger.h
# optimizer headers
/usr/include/nntrainer/optimizer_context.h
/usr/include/nntrainer/optimizer_devel.h
/usr/include/nntrainer/lr_scheduler.h
# pkg config and static binary
/usr/lib/*/pkgconfig/nntrainer.pc
/usr/lib/*/libnntrainer.a
# update this to enable external applications
# @todo filter out headers that should be hidden
/usr/include/nntrainer/util_func.h
/usr/include/nntrainer/fp16.h
/usr/include/nntrainer/util_simd.h
# model
/usr/include/nntrainer/neuralnet.h
