name: C++ Format Checker

on: pull_request

jobs:
  cpp-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cpp-linter/cpp-linter-action@v2.8.0
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: file
          version: 16
          lines-changed-only: true
          file-annotations: false
          step-summary: true

      - name: failing fast
        if: steps.linter.outputs.clang-format-checks-failed > 0
        run: |
          echo "This PR failed to pass the C++ source file format checks."
          exit 1
