# @author : Donghak Park <donghak.park@samsung.com>
# @file   : labeler.yml
# @date   : 15 Feb 2023

name: Auto Need-Review labeler

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
  pull_request_review:
    types: [edited, dismissed, submitted]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Get number of approved Review
        run: |
          reviews=$(curl -s -H "Accept: application/vnd.github.black-cat-preview+json" \
          https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews \
          | jq '[ .[] | select(.state=="APPROVED") ] | length')
          echo "Number of approved reviews: $reviews"
        id: review_count

      - name: Make label if approved review < 3
        if: ${{ steps.review_count.outputs.review_count < 3 && !contains(github.event.pull_request.labels.*.name, 'Need Review') }}
        uses: actions/github-script@v4
        with:
          script: |
            github.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ["Need Review"]
            })
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Remove label if approved review >= 3
        if: ${{ steps.review_count.outputs.review_count >= 3 && contains(github.event.pull_request.labels.*.name, 'Need Review') }}
        uses: actions/github-script@v4
        with:
          script: |
            github.issues.removeLabel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              name : ["Need Review"]
            })
          token: ${{ secrets.GITHUB_TOKEN }}
